apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugtracker-backend
  labels:
    app: bugtracker-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bugtracker-backend
  template:
    metadata:
      labels:
        app: bugtracker-backend
    spec:
      containers:
      - name: backend
        image: saiif/securebugtracker-backend:latest   # Jenkins will update this tag
        ports:
        - containerPort: 5000

